preset: laravel

enabled:

disabled:
  - length_ordered_imports
  - phpdoc_summary
  - phpdoc_var_without_name
  - post_increment
  - concat_without_spaces

finder:
  exclude:
    - "vendor"
    - "test"