preset: laravel

enabled:

disabled:
  - phpdoc_summary
  - phpdoc_var_without_name
  - post_increment
  - concat_without_spaces
  - alpha_ordered_imports

finder:
  exclude:
    - "vendor"
    - "test"